name: Hello World

# testing pull_request trigger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, Gabriel! This workflow ran automatically."
      - name: Use a secret
        run: echo "The secret value has length ${#MY_SECRET}"
        env:
          MY_SECRET: ${{ secrets.MY_TEST_SECRET }}
